name: Run tests on PR

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.ts'

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure environment variables
        run: cp .env.example .env
      - name: Generate RSA keys
        run: |
          openssl genrsa -out ./assets/rsa/private.pem 2048
          openssl rsa -in ./assets/rsa/private.pem -pubout -out ./assets/rsa/public.pem
      - name: Run tests
        run: |
          yarn
          yarn test
